on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/workflows/e2e-docusaurus-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Docusaurus'
jobs:
  chore:
    name: 'Validating Docusaurus'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Install Node'
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: 'Build the standard bundle'
      run: |
        node ./scripts/run-yarn.js build:cli

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        yarn dlx create-docusaurus@latest my-website classic && cd my-website
        yarn build

    - name: 'Running the TypeScript integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        yarn dlx create-docusaurus@latest my-website-ts classic --typescript && cd my-website-ts
        yarn build
      if: |
        always()
